version: '3.8'

services:
  db:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - '5432:5432'

  server:
    build:
      dockerfile: ./Server-Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - '8080:8080'
