import { Dictionary } from "../types";

const strings: Dictionary = {
  emailLabel: "Adres email",
  passwordLabel: "Hasło",
  nameLabel: "Nazwa użytkownika",
  signIn: "Zaloguj się",
  signUp: "Zarejestruj się",
  requiredField: "Pole wymagane",
  retypedPasswordLabel: "Powtórz hasło",
  invalidUsername:
    "Nazwa użytkownika powinna składać się z conajmniej 3 znaków",
  invalidEmail: "Nieprawidłowy adres email",
  passwordTooWeak:
    "Hasło powinno zawierać co najmniej 1 wielką i małą literę, znak specjalny oraz cyfrę",
  passwordsNotEquals: "Hasła nie są identyczne",
  analysis: "Analiza",
  payments: "Płatności",
  groups: "Grupy",
  settings: "Ustawienia",
  invalidCredentials: "Nieprawidłowe dane logowania",
  unknownError: "Ups... Coś poszło nie tak",
  createGroup: "Utwórz grupę",
  groupName: "Nazwa grupy",
  create: "Utwórz",
  addMember: "Dodaj członka",
  members: "Członkowie",
  searchPeople: "Szukaj znajomych",
  search: "Szukaj",
  noResults: "Brak wyników",
  noMembersYet: "Nie masz jeszcze dodanych żadnych członków",
  logout: "Wyloguj się",
  darkTheme: "Ciemny motyw",
  camera: "Aparat",
  gallery: "Galeria",
  addPicture: "Dodaj zdjęcie",
  delete: "Usuń",
  items: "Pozycje",
  add: "Dodaj",
  cancel: "Anuluj",
  name: "Nazwa",
  save: "Zapisz",
  addInvoice: "Dodaj paragon",
  toPay: "Do zapłaty",
  toReturn: "Do zwrotu",
  totalPrice: "Całkowita kwota",
  status: "Status",
  OPENED: "Do zapłaty",
  CLOSED: "Opłacone",
  PENDING: "W rozliczeniu",
  REJECTED: "Odrzucone",
  settlement: "Rozliczenie",
  addedBy: "Dodane przez",
  assignedToGroup: "Przypisane do grupy",
  forSettlement: "Do rozliczenia",
  receivables: "Należności",
  filter: "Filtruj",
  confirm: "Zatwierdź",
  reject: "Odrzuć",
  bankAccountNumber: "Numer konta bankowego",
  phoneNumber: "Numer telefonu",
  noConfidentialsProvided: "Nie podano danych do rozliczenia",
  pay: "Zapłać",
};

export default strings;
