create table if not exists p_user
(
    id bigint generated by default as identity
    constraint p_user_pkey
    primary key,
    avatar varchar(255),
    bank_account varchar(255),
    blik_number varchar(255),
    email varchar(255) not null
    constraint uk_ogywo3ggsigo9oljx32xua8hg
    unique,
    name varchar(255) not null,
    password varchar(255) not null,
    registration_time timestamp not null
    );

alter table p_user owner to postgres;

create table if not exists p_group
(
    id bigint generated by default as identity
    constraint p_group_pkey
    primary key,
    avatar varchar(255),
    creation_time timestamp not null,
    name varchar(255) not null,
    owner_id bigint not null
    constraint fkx9gr54gst2b31r2vx1db6lk6
    references p_user
    );

alter table p_group owner to postgres;

create table if not exists group_member
(
    join_time timestamp not null,
    nick varchar(255),
    group_id bigint not null
    constraint fk9apht2bh26psurcdcft2f7tr7
    references p_group,
    user_id bigint not null
    constraint fkmrwkwb6jrgdfp8euou50bvcmn
    references p_user,
    constraint group_member_pkey
    primary key (group_id, user_id)
    );

alter table group_member owner to postgres;

create table if not exists invoice
(
    id bigint generated by default as identity
    constraint invoice_pkey
    primary key,
    add_time timestamp not null,
    group_id bigint not null
    constraint fkaibwk9xoy7wl50wlx6awmu4im
    references p_group,
    user_id bigint not null
    constraint fknodb0rxacwyfur2jn8fv9df3t
    references p_user,
    name text,
    settled boolean
);

alter table invoice owner to postgres;

create table if not exists invoice_item
(
    id bigint generated by default as identity
    constraint invoice_item_pkey
    primary key,
    name varchar(255) not null,
    price double precision not null,
    invoice_id bigint
    constraint fkbu6tmpd0mtgu9wrw5bj5uv09v
    references invoice
    );

alter table invoice_item owner to postgres;

create table if not exists payment
(
    id bigint generated by default as identity
    constraint payment_pkey
    primary key,
    price double precision not null,
    invoice_id bigint
    constraint fksb24p8f52refbb80qwp4gem9n
    references invoice,
    user_id bigint
    constraint fk98984vdaycr8tr1nnb49v49jb
    references p_user
);

alter table payment owner to postgres;

create table if not exists payment_status
(
    id bigint generated by default as identity
    constraint payment_status_pkey
    primary key,
    name varchar(255)
    );

alter table payment_status owner to postgres;

create table if not exists payment_history
(
    id bigint generated by default as identity
    constraint payment_history_pkey
    primary key,
    time timestamp not null,
    payment_id bigint
    constraint fkrgfm32kn93gp9q6e5jcoaf5f7
    references payment,
    payment_status_id bigint
    constraint fk83n0fb3ueudgkr6pyeo942ig5
    references payment_status
);

alter table payment_history owner to postgres;

create table if not exists photo
(
    id bigint generated by default as identity
    constraint photo_pkey
    primary key,
    creation_time timestamp not null,
    path varchar(255) not null,
    invoice_id bigint
    constraint fkkplrlvwau00hbaqeo7rn2dd5o
    references invoice
    );

alter table photo owner to postgres;

create table if not exists token
(
    value varchar(255) not null
    constraint token_pkey
    primary key,
    expiration_time timestamp not null,
    user_id bigint
    constraint fkl4bmvclnjx085wp2xde6hahm1
    references p_user
    );

alter table token owner to postgres;

